### ISSUE TITLE
你好，请问win版右键能否添加一个“删除当前壁纸”的选项

### ISSUE THREAD

**Issue by jerry011235** [redstoneleo/BingNiceWallpapers#4]
你好，请问win版右键能否添加一个“删除当前壁纸”的选项，因为有些壁纸如果个人不喜欢，就可以点击“删除当前壁纸”，同时点击后，程序自动转到 **前一天的壁纸** 为桌面（或者随机从壁纸库里取一张为桌面皆可）。
而这也减少了一些人用老电脑，硬盘小的压力，毕竟一天一张图，日积月累的容量也是很大的。
同时提供一个壁纸源：http://wallpaper.daoapp.io/
https://www.bing.com/gallery/#

**Comment by redstoneleo** [comment]
“删除当前壁纸”正在谋划中，欢迎贡献代码

**Comment by redstoneleo** [comment]
新版已添加
