### ISSUE TITLE
双屏能否显示不同的壁纸:)

### ISSUE THREAD

**Issue by we4p0x** [redstoneleo/BingNiceWallpapers#5]
在win10上双屏只能显示相同壁纸呀

**Comment by celeron533** [comment]
这似乎是windows的功能限制

**Comment by redstoneleo** [comment]
我没用win10，你可以研究下

**Comment by celeron533** [comment]
发现可以这么做了。。。
https://www.groovypost.com/howto/set-different-wallpaper-backgrounds-dual-monitors-windows-10/

![image](https://cloud.githubusercontent.com/assets/3608762/21717711/c023c6e6-d44d-11e6-8693-a432e1fbc2b6.png)

![image](https://cloud.githubusercontent.com/assets/3608762/21717712/c4d0b2d0-d44d-11e6-9d15-6013ca2cd6fd.png)

![image](https://cloud.githubusercontent.com/assets/3608762/21717714/c83a8dba-d44d-11e6-96f0-f3b387f37163.png)

![image](https://cloud.githubusercontent.com/assets/3608762/21717717/cc083e7e-d44d-11e6-97c5-628016a5712d.png)
