### ISSUE TITLE
删除壁纸，再左键切换壁纸，会黑屏（无壁纸）

### ISSUE THREAD

**Issue by jerry011235** [redstoneleo/BingNiceWallpapers#7]
win10系统，删除“必应好壁纸壁纸库”文件夹里的几张壁纸后，只保留两三张壁纸，再左键点击任务栏图标，切换壁纸，会出现黑屏（无壁纸现象）。
下图为多次左键任务栏图标切换壁纸的gif：
http://ww4.sinaimg.cn/large/a15b4afegw1fbh5xeiuecg21gn0qib2k

**Comment by redstoneleo** [comment]
出现黑壁纸的时候，鼠标在托盘图标右键，看看能否删除这张黑壁纸？

**Comment by jerry011235** [comment]
右键选择“删除壁纸”后，马上任务栏图标消失，程序自动结束。即任务管理器里`BingNiceWallpapers.exe`突然消失了。
再运行程序，再对着黑壁纸删除，眼睁睁地看着这个进程消失。
再打开，右键“更多功能”，发现收藏壁纸路径为`C:/Users/<我的用户名>/Pictures\收藏的必应壁纸`，而不是我自定义的路径`E:\Pictures\必应好壁纸壁纸库\收藏的必应壁纸`。
配置文件：
```
[General]
pathToWallpaperDir=E:\\Pictures
timeoutInterval=600000
pathToLikedWallpaperDir=C:/Users/<我的用户名>/Pictures
```

**Comment by redstoneleo** [comment]
贴出C:/Users/<我的用户名>/Movies/BingNiceWallpapers.log的内容看看

**Comment by jerry011235** [comment]
log在[这里](https://github.com/jerry011235/test/blob/master/66/BingNiceWallpapers.log)

**Comment by jerry011235** [comment]
问题差不多弄明白了：
1.重装好壁纸，正常的配置文件
```
[General]
pathToWallpaperDir=C:/Users/<我的用户名>/AppData/Roaming/iMath
timeoutInterval=600000
pathToLikedWallpaperDir=C:/Users/<我的用户名>/Pictures
```
这时如果右键任务栏图标，更改保存位置：
壁纸库：`E:\Pictures\必应好壁纸壁纸库`
收藏：`E:\Pictures\必应好壁纸壁纸库\收藏的必应壁纸`
确定后，退出软件，再打开，发现壁纸库位置又**强制**变回来成`C:/Users/<我的用户名>/AppData/Roaming/iMath\必应好壁纸壁纸库`，并且ini文件也是`
pathToWallpaperDir=C:/Users/<我的用户名>/AppData/Roaming/iMath`，这时并无黑壁纸现象。
此时的log：
```
01/07 10:21:00 PM Uncaught exception
Traceback (most recent call last):
  File "BingNiceWallpapers.pyw", line 368, in checkNewVersion
AttributeError: 'QAction' object has no attribute 'readAll'
```
2.退出软件，手动删除`C:\Users\用户名\AppData\Roaming\iMath\必应好壁纸壁纸库`文件夹，并且手动编辑ini文件为`pathToWallpaperDir=E:\\Pictures`。
打开软件，则会出现上述的黑壁纸现象。
此时的log并没有增加。
3.手动编辑ini，改回`
pathToWallpaperDir=C:/Users/<我的用户名>/AppData/Roaming/iMath`，同时复制图片到此文件夹，打开软件，无黑壁纸现象。
log：
```
01/07 10:34:35 PM Uncaught exception
Traceback (most recent call last):
  File "BingNiceWallpapers.pyw", line 316, in changeWallpaper
AttributeError: 'BingNiceWallpapers' object has no attribute 'wallpapers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "random.py", line 253, in choice
  File "random.py", line 230, in _randbelow
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BingNiceWallpapers.pyw", line 320, in changeWallpaper
  File "random.py", line 255, in choice
IndexError: Cannot choose from an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BingNiceWallpapers.pyw", line 312, in iconActivated
  File "BingNiceWallpapers.pyw", line 322, in changeWallpaper
UnboundLocalError: local variable 'l' referenced before assignment
```

**Comment by redstoneleo** [comment]
谢谢你花功夫研究这么多！！！
1.针对问题1，我改了下代码，这下子应该好了，请到这里下载新版试试看 http://cloud.189.cn/t/Rr2UR3VN7Jny
2. 根据log来看
`PermissionError: [WinError 5] 拒绝访问。: 'E:\\Pictures\\必应好壁纸壁纸库\\收藏的必应壁纸'`
首先你不能把“收藏的必应壁纸”文件夹发到“必应好壁纸壁纸库”文件夹里去，因为“必应好壁纸壁纸库”文件夹只能放图片，其他的任何文件类型或文件夹都不能放，所以你这里才会出问题，另外如果你避免了上述这个问题，那么把如果把“收藏的必应壁纸”和“必应好壁纸壁纸库”两个文件夹安排在E盘，结果还是会黑屏，那么可能是本软件不具有访问E盘的权限，请以管理员是否启动软件试试看。另外，你要确保新的壁纸存储路径是不存在的才能修改壁纸保存位置
3.手动编辑ini是不推荐的，那是给软件读写的，不供人编辑

**Comment by jerry011235** [comment]
感谢修正。下载最新版后完美解决。
要点：1.`收藏的必应壁纸`文件夹不能被包含在`必应好壁纸壁纸库`文件夹里。
2.如果你的自定义目录为`E:\Pictures\bing好壁纸\必应好壁纸壁纸库`和`E:\Pictures\bing好壁纸\收藏的必应壁纸`，那么**更改设置前**必须保证`E:\Pictures\bing好壁纸`目录里为空。
再次感谢，可以关闭问题了。

**Comment by redstoneleo** [comment]
更改设置前必须保证`E:\Pictures\bing好壁纸`目录不含有`收藏的必应壁纸`文件夹和`必应好壁纸壁纸库`文件夹就行！
